services:
  provider:
    image: ghcr.io/pekempy/encoraplexprovider:latest
    container_name: encora-plex-provider
    restart: unless-stopped
    ports:
      - "${PORT:-32441}:${PORT:-32441}"
    env_file:
      - .env
    environment:
      - ENCORA_API_KEY=${ENCORA_API_KEY}
      - STAGEMEDIA_API_KEY=${STAGEMEDIA_API_KEY}
      - PORT=${PORT:-32441}
      - PLEX_LIBRARY_BASE_PATH=${PLEX_LIBRARY_BASE_PATH}
    volumes:
      - ${PLEX_LIBRARY_BASE_PATH}:${PLEX_LIBRARY_BASE_PATH}:ro
